# Generated by Django 4.0.2 on 2022-03-17 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_category_alter_product_date_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_new',
            field=models.CharField(blank=True, choices=[('Old', 'Old'), ('New', 'New')], max_length=10, null=True, verbose_name='Choose New & Old'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 0, 57, 10, 881522)),
        ),
    ]
