# Generated by Django 4.0.3 on 2022-03-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True),
        ),
    ]
