# Generated by Django 4.0.3 on 2022-03-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_coupon_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
